version: '3'
services:
  api:
    container_name: todo-api
    build:
      context: ./
    depends_on:
      - cache
      - db
    ports:
      - 5001:5001
    links:
      - cache
  client:
    build: ../client
    container_name: todo-client
    depends_on:
      - api
    ports:
      - '3000:3000'
    volumes:
      - client_volume:/app
    stdin_open: true

  db:
    image: postgres:12-alpine
    container_name: todo-db
    ports:
      - '5433:5432'  
    environment:      
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'docker_learning'
    volumes:
      - db_volume:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:6.2-alpine
    container_name: todo-cache
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes: 
      - cache_volume:/data
    restart: always

volumes:
  cache_volume:
  db_volume:
  api_volume:
  client_volume: