version: "3"
services:
  api:
    build: ./
    container_name: api_c
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - api_volume:/app
      - ./app/node_modules
    restart: always

  client:
    build: ../client
    container_name: client_c
    depends_on:
      - api
    ports:
      - '3000:3000'
    volumes:
      - client_volume:/app
      - ./app/node_modules
    stdin_open: true
  
  db:
    image: postgres:12-alpine
    container_name: db_c
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'  
    environment:      
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'docker_learning'
    restart: always

volumes:
  db_data:
  api_volume:
  client_volume: