version: "3"
services:
  api:
    build: ./
    container_name: api_c
    ports:
      - '5000:5000'
    depends_on:
      - db
      - cache
    volumes:
      - api_volume:/app
    restart: always
    links:
      - cache
      - db

  client:
    build: ../client
    container_name: client_c
    depends_on:
      - api
    ports:
      - '3000:3000'
    volumes:
      - client_volume:/app
    stdin_open: true
  
  db:
    image: postgres:12-alpine
    container_name: db_c
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'  
    environment:      
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'docker_learning'
    restart: always

  cache:
    image: redis:6.2-alpine
    container_name: cache_c
    restart: always
    ports:
      - '6380:6379'
    volumes: 
      - cache_volume:/data

volumes:
  db_data:
  api_volume:
  client_volume:
  cache_volume: